apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: sleep-30sec-container
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'sleep 30']
      containers:
        - name: job-service
          image: us-central1-docker.pkg.dev/tmv-checklist-dev/docker-image-registry/checklist-job:TAG
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
              ephemeral-storage: '2Gi'
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: db
            - name: AUTHORIZATION_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: authorization-endpoint
---
# job-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: job-srv
spec:
  type: ClusterIP
  selector:
    app: job-service
  ports:
    - name: job
      protocol: TCP
      port: 3000
      targetPort: 3000
