apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init-bucket-job
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 4
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: minio-init-bucket-job
          image: minio/mc:latest
          resources:
            limits:
              memory: '256Mi'
              cpu: '100m'
              ephemeral-storage: '2Gi'
          command: ['/bin/sh']
          args:
            - '-c'
            - 'mc mb minio/$(MEDIA_BUCKET) --ignore-existing'
          env:
            - name: MEDIA_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: minio-configmap
                  key: media-bucket
            - name: MC_HOST_minio
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: mc-host-url
