export const COMPANY_REPOSITORY = Symbol('COMPANY_REPOSITORY');
export const BILLING_CONTACT_REPOSITORY = Symbol('BILLING_CONTACT_REPOSITORY');
export const COMPANY_TENANT_REPOSITORY = Symbol('COMPANY_TENANT_REPOSITORY');
