export enum ErrorCode {
  INDUSTRY_NOT_FOUND = 'industry.not-found',
  CATEGORY_NOT_FOUND = 'category.not-found',
  VALIDATION_ERROR = 'validation.error',
  INPUT_TYPE_NOT_FOUND = 'input-type.not-found',
  TEMPLATE_NOT_FOUND = 'template.not-found',
  NOT_AUTHORIZED = 'auth.not-authorized',
  FORBIDDEN = 'auth.forbidden',
  USER_ALREADY_EXISTS = 'register.user_already_exists',
  WRONG_CREDENTIALS = 'login.wrong_credentials',
  BAD_VERIFICATION_REQUEST = 'email-verification.bad-request',
  USER_NOT_FOUND = 'user.not-found',
  CAPTCHA_TOKEN_VERIFICATION_FAILED = 'captcha.token verification-failed',
  INTERNAL_SERVER_ERROR = 'server.internal-server-error',
  PASSWORD_RESET_TOKEN_EXPIRED_OR_INVALID = 'password-reset.token-expired-or-invalid',
  PASSWORD_RESET_TOKEN_INVALID = 'password-reset.token-invalid',
  TOO_MANY_REQUESTS = 'auth.too-many-requests',
  JOB_NOT_FOUND = 'job.not-found',
  EMAIL_IN_USE = 'register.email-in-use',
  JOB_UPDATE_STATUS_VALIDATION_ERROR = 'job.job-update-statue-validation-error',
}
