export const INDUSTRY_REPOSITORY = Symbol('INDUSTRY_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const TEMPLATE_REPOSITORY = Symbol('TEMPLATE_REPOSITORY');
export const TASK_REPOSITORY = Symbol('TASK_REPOSITORY');
export const INPUT_TYPE_REPOSITORY = Symbol('INPUT_TYPE_REPOSITORY');
